### PR TITLE
remove unexpected side effect: do not clean expectedEvents

### PR DESCRIPTION
**Pull request by Gorynych**

### CODE REVIEW

**Comment by bkrahmer** [comment]
when submitting PRs, please don't commit the version bump.  there is now a conflict and it must be resolved before merging

**Comment by Gorynych** [comment]
What should I do in case of interface changes?

**Comment by bkrahmer** [comment]
Do you mean in general, if you want to change an interface?  In that case, we need to agree the change should be made, and then I will bump the minor version.  This does not look to be a breaking change, so  please revert changes to gradle.properties altogether.

**Comment by Gorynych** [comment]
Done

**Pull request closed without merging**
